// 实用库/Vue3 Vite3 TS Pinia Vue-Router ESLint/src/App.vue
<script setup lang="ts">
import HelloWorld from '@/components/HelloWorld.vue'
import Logo from '@assets/images/logo.svg'
</script>

<template>
    <div>
        <a href="https://vitejs.dev" target="_blank" rel="noreferrer noopener">
            <Logo />
        </a>
        <a href="https://vuejs.org/" target="_blank" rel="noreferrer noopener">
            <img src="./assets/vue.svg" class="logo vue" alt="Vue logo">
        </a>
    </div>
    <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
}

.logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
    filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// 实用库/React18 Vite3 ESLint Vitest TypeScript/src/App.tsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'


const App = () => {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <div>
        <a href="https://vitejs.dev" rel="noreferrer" target="_blank">
          <img alt="Vite logo" className="logo" src="/vite.svg" />
        </a>
        <a href="https://reactjs.org" rel="noreferrer" target="_blank">
          <img alt="React logo" className="logo react" src={reactLogo} />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => void setCount(count => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </div>
  )
}

export default App
